### ISSUE TITLE
HandBrakeCLI version unknown

### ISSUE THREAD

**Issue by paulbailey** [donmelton/video_transcoding#29]
I believe this is happening because I am using a nightly version of HandbrakeCLI, and their repository is now hosted on GitHub. Obviously it's not parsing correctly, but even if it did, I think it's going to fail the version number check (which seems based on a svn commit number)

    $ HandBrakeCLI --version
    [13:11:17] hb_init: starting libhb thread
    [13:11:17] thread 700000081000 started ("libhb")
    HandBrake 20151209210633-3443f6a-master

**Comment by donmelton** [comment]
@paulbailey Ouch. Sorry about that. Yeah, my current code assumes an official `HandBrakeCLI` release or development build based on a SVN commit number. The development version of `HandBrakeCLI` you have appears to based on Git.

God willing the first part of that Git string is the date. So, maybe I can parse that for a comparison. Do you know what the format is?

Also, does the string always end in "-master?" If it does, that makes it much simpler.

**Comment by paulbailey** [comment]
I'll check the upstream source/build process to be sure, but it's a datetimestamp, with the latest commit and build branch attached, as far as I can tell. Will update the issue with details when I'm next in front of an actual computer!

On 14 Dec 2015, at 15:55, Don Melton <notifications@github.com<mailto:notifications@github.com>> wrote:


@paulbailey<https://github.com/paulbailey> Ouch. Sorry about that. Yeah, my current code assumes an official HandBrakeCLI release or development build based on a SVN commit number. The development version of HandBrakeCLI you have appears to based on Git.

God willing the first part of that Git string is the date. So, maybe I can parse that for a comparison. Do you know what the format is?

Also, does the string always end in "-master?" If it does, that makes it much simpler.

-

**Comment by donmelton** [comment]
@paulbailey Thanks! Yeah, I won't be able to fix this for a few days anyway because I'm traveling so no hurry.

**Comment by paulbailey** [comment]
@donmelton It's as suspected. The "master" refers to the branch, and it seems unlikely they'd post nightly builds from anywhere else, as a matter of course. 

I can do a pull request with appropriate changes if that would help? No rush from my end, I'll make appropriate changes locally so I can use the nightly build (it handles 5.1 properly for the new Apple TVs).

**Comment by donmelton** [comment]
@paulbailey Sure. I'll evaluate your pull request. That could save me some time, too. No hurry, though. I'll probably take a look at this on Wednesday.

**Comment by paulbailey** [comment]
Hmm. So just to update you, @donmelton, I forked the repo to put together a pull request. It seems as though the output is significantly different between the release version, and the current nightly. I see you're using `--preset-list` to get the version details. Here's what the nightly produces for the same command:

```
$ HandbrakeCLI --preset-list
[10:21:10] hb_init: starting libhb thread
[10:21:10] thread 700000081000 started ("libhb")
Devices/
    Universal
        HandBrake's settings for compatibility with all Apple
        devices (including the iPod 6G and later). Includes Dolby
        Digital audio for surround sound.
    iPod
        HandBrake's settings for playback on the iPod with Video
        (all generations).
    iPhone & iPod touch
        HandBrake's settings for handheld iOS devices (iPhone 4,
        iPod touch 3G and later).
    iPad
        HandBrake's settings for playback on the iPad (all
        generations).
    AppleTV
        HandBrake's settings for the original AppleTV. Includes
        Dolby Digital audio for surround sound. Also compatible with
        iOS devices released since 2009.
    AppleTV 2
        HandBrake's settings for the second-generation AppleTV.
        Includes Dolby Digital audio for surround sound. NOT
        compatible with the original AppleTV.
    AppleTV 3
        HandBrake's settings for the third-generation AppleTV.
        Includes Dolby Digital audio for surround sound. NOT
        compatible with the original AppleTV. May stutter on the
        second-generation AppleTV.
    Android
        HandBrake's settings for midrange devices running Android
        2.3 or later.
    Android Tablet
        HandBrake's preset for tablets running Android 2.3 or later.
    Windows Phone 8
        HandBrake's preset for Windows Phone 8 devices
Regular/
    Normal
        HandBrake's normal, default settings.
    High Profile
        HandBrake's general-purpose preset for High Profile H.264
        video.
```

No version number, and significantly different output. As you've probably noticed, they've implemented a `--version` option now though.

The pull request might take a little longer than I'd hoped...

**Comment by donmelton** [comment]
@paulbailey Thanks! I didn't know they had implemented a `--version` option. Finally!

Well, that'll make code to do the check a bit more complicated then. I'll have to try both of the options then. Not sure which to do first yet, but I'll figure it out.

**Comment by donmelton** [comment]
@paulbailey I'm considering just pulling the version checking completely. Maybe just a check for the really old versions of `HandBrakeCLI`. For one thing, I have no idea what the final version string for the next release will look like.

**Comment by paulbailey** [comment]
@donmelton I guess this is part of the hassle with wrapping CLI tools. If there were no version-checking, what would happen with an older version? Unexpected errors I guess. 

Happily enough, the reason I was using a nightly build, 5.1 audio fallback handling for different behaviour by the new Apple TV, [fixed here](https://github.com/HandBrake/HandBrake/commit/638e83c3371eb0ac3490b9db90b6be865ccd9904), was actually fixed first by Apple with the tvOS 9.1 release!

**Comment by donmelton** [comment]
@paulbailey I've just checked in a fix to no longer fail if the HandBrake version string isn't in the output of `HandBrakeCLI --preset-list`. This allows current post-0.10.2 nightly builds but still fails for pre-0.10.0 builds. That'll have to do until the next official release of HandBrake.

I'll leave this open until I make an official release, probably early next week.

**Comment by donmelton** [comment]
@paulbailey Just do a `gem update` to get version 0.2.8 with the fix. :)
